services:
  web:
    image: nginx:latest
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - "8080:80"

  db:
    image: postgres:latest
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      POSTGRES_PASSWORD: lab_password